### ISSUE TITLE
file is not created

### ISSUE THREAD

**Issue by kashifansari786** [kk121/File-Loader#1]
when i select DIR_EXTERNAL_PRIVATE or DIR_EXTERNAL_PUBLIC it is not created any file directory and not even download any file why this is happen.

**Comment by kk121** [comment]
You need to declare FIle write permission in manifest.
```java
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
If you are targeting API level >= 23 (Marshmallow) then you also need to ask for run time permission.
https://developer.android.com/training/permissions/requesting.html

**Comment by kashifansari786** [comment]
Dear krishna it is already done by me but there is no download the file is
not created and download is not started download is only done when
dir_internal is choose otherwise no download is done.

**Comment by kk121** [comment]
Hi @kashifansari786 ,
Please upgrade to latest version v1.1:
``
compile 'com.github.kk121:File-Loader:v1.1'
``

If you still face the issue, then please attach the exception message:
```java
@Override 
 public void onError(FileLoadRequest request, Throwable t) {
   Log.d(TAG, "onError: " + t.getMessage());
 }
```

**Comment by kashifansari786** [comment]
see my code is below and there is no error show in error log and the file which it is stored is in number format(like 1933563718 coz you set uri in hashcode) and it don't have any extension so that no application is detect that file.can you help me out from this i have images and audio also to download and i want images are saved in Environment.DIRECTORY_PICTURES and audio in Environment.DIRECTORY_MUSIC thanks you.
 List<MultiFileLoadRequest> multiFileLoadRequests = new ArrayList<>();
        multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getProfile_image(), "test2", FileLoader.DIR_EXTERNAL_PUBLIC, true));
        multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getSet_image(), "test2", FileLoader.DIR_EXTERNAL_PUBLIC, true));
        multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getAudio(), "test4", FileLoader.DIR_EXTERNAL_PUBLIC, true));


        MultiFileDownloader multiFileDownloader = FileLoader.multiFileDownload(getActivity());
        multiFileDownloader.progressListener(new MultiFileDownloadListener() {
            @Override
            public void onProgress(File downloadedFile, int progress, int totalFiles) {

            }

            @Override
            public void onError(Exception e, int progress) {
                super.onError(e, progress);
                Log.d("insideerrorlog", "onError: " + e.getMessage());
            }
        }).loadMultiple(true, multiFileLoadRequests);

**Comment by kk121** [comment]
Hi @kashifansari786,
I have released one more version (1.2) which supports file download with name and extension.
Please upgrade to latest version 1.2:
```java
compile 'com.github.kk121:File-Loader:1.2'
```
Now your request should be:
```java
List multiFileLoadRequests = new ArrayList<>();
multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getProfile_image(), Environment.DIRECTORY_PICTURES, FileLoader.DIR_EXTERNAL_PUBLIC, false));
multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getSet_image(), Environment.DIRECTORY_PICTURES, FileLoader.DIR_EXTERNAL_PUBLIC, false));
multiFileLoadRequests.add(new MultiFileLoadRequest(down.get(0).getAudio(), Environment.DIRECTORY_MUSIC, FileLoader.DIR_EXTERNAL_PUBLIC, false));

MultiFileDownloader multiFileDownloader = FileLoader.multiFileDownload(getActivity());
    multiFileDownloader.progressListener(new MultiFileDownloadListener() {
        @Override
        public void onProgress(File downloadedFile, int progress, int totalFiles) {

        }

        @Override
        public void onError(Exception e, int progress) {
            super.onError(e, progress);
            Log.d("insideerrorlog", "onError: " + e.getMessage());
        }
    }).loadMultiple(multiFileLoadRequests);
```
Hope it helps.

**Comment by kashifansari786** [comment]
I changed directory file and then i have to change file diatination and its file extension it is fine but okhttp api is really very slow if i want to download a playlist which contain 3 files and each file have 3 diffrent files then it takes hell of time to download and secondly the you have to give callback of total bytes and the bytes which is downloaded so that progress bar is implemented, you give total file size that call back is not sufficient to implement progress bar.if you work on this that is appriciated

**Comment by cstar-99** [comment]
Could not find com.github.kk121:File-Loader:1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
       - https://jcenter.bintray.com/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
     Required by:
         project :app
How to solve this
