### ISSUE TITLE
ERROR: Failed to resolve: com.github.kk121:File-Loader:1.2

### ISSUE THREAD

**Issue by rupeshSingh7** [kk121/File-Loader#9]
i write dependency and syn the project

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
    
dependencies {
    implementation 'com.github.kk121:File-Loader:1.2'
}

**Comment by salveta** [comment]
Hi, did you found some fix for this???

**Comment by Pcol10** [comment]
You should add maven's to **allprojects** repositories, and it should looks like this:
### Code example
`allprojects {
 repositories { 
***
 mavenCentral() 
 maven { url 'https://maven.google.com' 
 }
}`
Sometimes poeple are misinformed and add it to **buildscript**.

**Comment by gokdayi** [comment]
As stated in this tutorial; https://blog.mindorks.com/how-to-open-a-pdf-file-in-android-programmatically You can define repositories like this;

```
repositories {
    google()
    jcenter()
    maven {url "https://jitpack.io"}//add this line
}
```

**Comment by cstar-99** [comment]
Could not find com.github.kk121:File-Loader:1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
       - https://jcenter.bintray.com/com/github/kk121/File-Loader/1.2/File-Loader-1.2.pom
     Required by:
         project :app

how solve this error

**Comment by rupeshSingh7** [comment]
yes i founded solution thanks for support
